-- Drop tables in reverse order of creation to avoid foreign key constraint violations
DROP MATERIALIZED VIEW MV_AEROPUERTOS_COMPAGNIAS;
DROP MATERIALIZED VIEW MV_COMPAGNIA_MAX_AVIONES;
DROP MATERIALIZED VIEW RETRASOS_COMPAGNIAS;
DROP TABLE Retraso;
DROP TABLE Desvio;
DROP TABLE Cancelacion;
DROP TABLE Vuelo;
DROP TABLE Avion;
DROP TABLE Modelo;
DROP TABLE Fabricante;
DROP TABLE Compagnia;
DROP TABLE Aeropuerto;