WITH RETRASOS_COMPAGNIAS AS (
    SELECT 
	    V.Company AS Codigo_Compania,
	    AVG(R.Duracion) AS Retraso_Promedio
	FROM Vuelo V
	JOIN Retraso R ON V.ID = R.ID_Vuelo
	WHERE R.Duracion IS NOT NULL
	GROUP BY V.Company
),
COMPANIAS_VUELOS_MINIMOS AS (
    SELECT 
        V.Company AS Codigo_Compania,
        V.Fecha,
        COUNT(V.ID) AS Total_Vuelos
    FROM Vuelo V
    GROUP BY V.Company, V.Fecha
    HAVING COUNT(V.ID) >= 1000
),
COMPANIAS_CUMPLEN_REQUISITO_DIAS AS (
	SELECT Codigo_Compania
	FROM COMPANIAS_VUELOS_MINIMOS
	GROUP BY Codigo_Compania
	HAVING COUNT(*) = 3
)
SELECT C.NOMBRE AS NOMBRE, RC.RETRASO_PROMEDIO
FROM RETRASOS_COMPAGNIAS RC, COMPANIAS_CUMPLEN_REQUISITO_DIAS CR, COMPAGNIA C
WHERE RC.CODIGO_COMPANIA = CR.CODIGO_COMPANIA AND C.CODIGO = CR.CODIGO_COMPANIA AND C.CODIGO = RC.CODIGO_COMPANIA; 