EXPLAIN PLAN FOR SELECT A.IATA, A.Nombre, A.Estado
FROM Aeropuerto A
WHERE A.IATA NOT IN (SELECT dest FROM MV_AEROPUERTOS_COMPAGNIAS)
  AND A.IATA NOT IN (SELECT sali FROM MV_AEROPUERTOS_COMPAGNIAS)
  AND A.Estado IN ('AK', 'CA');