INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LAX', 'CA', 'USA', 'Los Angeles');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('JFK', 'NY', 'USA', 'New York');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SFO', 'CA', 'USA', 'San Francisco');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LAS', 'NV', 'USA', 'Las Vegas');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ORD', 'IL', 'USA', 'Chicago');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LGA', 'NY', 'USA', 'New York');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('STT', 'VI', 'USA', 'Charlotte Amalie');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MIA', 'FL', 'USA', 'Miami');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DFW', 'TX', 'USA', 'Dallas-Fort Worth');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PHL', 'PA', 'USA', 'Philadelphia');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('STL', 'MO', 'USA', 'St Louis');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DCA', 'VA', 'USA', 'Arlington');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IAH', 'TX', 'USA', 'Houston');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BNA', 'TN', 'USA', 'Nashville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HNL', 'HI', 'USA', 'Honolulu');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OGG', 'HI', 'USA', 'Kahului');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BOS', 'MA', 'USA', 'Boston');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IAD', 'VA', 'USA', 'Chantilly');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EWR', 'NJ', 'USA', 'Newark');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SAN', 'CA', 'USA', 'San Diego');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MCO', 'FL', 'USA', 'Orlando');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('KOA', 'HI', 'USA', 'Kailua/Kona');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SEA', 'WA', 'USA', 'Seattle');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TUS', 'AZ', 'USA', 'Tucson');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LIH', 'HI', 'USA', 'Lihue');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RDU', 'NC', 'USA', 'Raleigh');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TPA', 'FL', 'USA', 'Tampa');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PHX', 'AZ', 'USA', 'Phoenix');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BWI', 'MD', 'USA', 'Baltimore');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SNA', 'CA', 'USA', 'Santa Ana');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SJC', 'CA', 'USA', 'San Jose');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RSW', 'FL', 'USA', 'Ft. Myers');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MCI', 'MO', 'USA', 'Kansas City');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MSY', 'LA', 'USA', 'New Orleans');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BHM', 'AL', 'USA', 'Birmingham');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PSP', 'CA', 'USA', 'Palm Springs');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SAT', 'TX', 'USA', 'San Antonio');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('XNA', 'AR', 'USA', 'Fayetteville/Springdale/Rogers');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DEN', 'CO', 'USA', 'Denver');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PDX', 'OR', 'USA', 'Portland');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ATL', 'GA', 'USA', 'Atlanta');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BDL', 'CT', 'USA', 'Windsor Locks');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RIC', 'VA', 'USA', 'Richmond');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MFE', 'TX', 'USA', 'McAllen');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FAT', 'CA', 'USA', 'Fresno');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ELP', 'TX', 'USA', 'El Paso');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MSP', 'MN', 'USA', 'Minneapolis');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ONT', 'CA', 'USA', 'Ontario');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OKC', 'OK', 'USA', 'Oklahoma City');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IND', 'IN', 'USA', 'Indianapolis');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ABQ', 'NM', 'USA', 'Albuquerque');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PBI', 'FL', 'USA', 'West Palm Beach');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SJU', 'PR', 'USA', 'San Juan');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('JAX', 'FL', 'USA', 'Jacksonville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AUS', 'TX', 'USA', 'Austin');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MEM', 'TN', 'USA', 'Memphis');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SLC', 'UT', 'USA', 'Salt Lake City');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DTW', 'MI', 'USA', 'Detroit');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BUR', 'CA', 'USA', 'Burbank');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FLL', 'FL', 'USA', 'Ft. Lauderdale');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CMH', 'OH', 'USA', 'Columbus');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RNO', 'NV', 'USA', 'Reno');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ICT', 'KS', 'USA', 'Wichita');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TUL', 'OK', 'USA', 'Tulsa');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('COS', 'CO', 'USA', 'Colorado Springs');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ORF', 'VA', 'USA', 'Norfolk');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SMF', 'CA', 'USA', 'Sacramento');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CLT', 'NC', 'USA', 'Charlotte');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DAY', 'OH', 'USA', 'Dayton');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('STX', 'VI', 'USA', 'Christiansted');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OMA', 'NE', 'USA', 'Omaha');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GSO', 'NC', 'USA', 'Greensboro');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SDF', 'KY', 'USA', 'Louisville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HSV', 'AL', 'USA', 'Huntsville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EGE', 'CO', 'USA', 'Eagle');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SCC', 'AK', 'USA', 'Deadhorse');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BRW', 'AK', 'USA', 'Barrow');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ANC', 'AK', 'USA', 'Anchorage');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OTZ', 'AK', 'USA', 'Kotzebue');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OME', 'AK', 'USA', 'Nome');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ADQ', 'AK', 'USA', 'Kodiak');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BET', 'AK', 'USA', 'Bethel');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FAI', 'AK', 'USA', 'Fairbanks');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('KTN', 'AK', 'USA', 'Ketchikan');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('JNU', 'AK', 'USA', 'Juneau');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('YAK', 'AK', 'USA', 'Yakutat');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CDV', 'AK', 'USA', 'Cordova');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SIT', 'AK', 'USA', 'Sitka');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PSG', 'AK', 'USA', 'Petersburg');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('WRG', 'AK', 'USA', 'Wrangell');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ADK', 'AK', 'USA', 'Adak');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OAK', 'CA', 'USA', 'Oakland');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LGB', 'CA', 'USA', 'Long Beach');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GEG', 'WA', 'USA', 'Spokane');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BUF', 'NY', 'USA', 'Buffalo');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SYR', 'NY', 'USA', 'Syracuse');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BTV', 'VT', 'USA', 'Burlington');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ROC', 'NY', 'USA', 'Rochester');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SRQ', 'FL', 'USA', 'Sarasota');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SWF', 'NY', 'USA', 'Newburgh');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HPN', 'NY', 'USA', 'White Plains');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PWM', 'ME', 'USA', 'Portland');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HOU', 'TX', 'USA', 'Houston');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BQN', 'PR', 'USA', 'Aguadilla');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PSE', 'PR', 'USA', 'Ponce');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PIT', 'PA', 'USA', 'Pittsburgh');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CLE', 'OH', 'USA', 'Cleveland');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BTR', 'LA', 'USA', 'Baton Rouge');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CVG', 'KY', 'USA', 'Covington');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GSP', 'SC', 'USA', 'Greer');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GPT', 'MS', 'USA', 'Gulfport-Biloxi');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TLH', 'FL', 'USA', 'Tallahassee');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PNS', 'FL', 'USA', 'Pensacola');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SAV', 'GA', 'USA', 'Savannah');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DAB', 'FL', 'USA', 'Daytona Beach');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MOB', 'AL', 'USA', 'Mobile');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LIT', 'AR', 'USA', 'Little Rock');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MLB', 'FL', 'USA', 'Melbourne');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('JAN', 'MS', 'USA', 'Jackson');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MKE', 'WI', 'USA', 'Milwaukee');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CHS', 'SC', 'USA', 'Charleston');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('VPS', 'FL', 'USA', 'Valparaiso');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TYS', 'TN', 'USA', 'Knoxville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BOI', 'ID', 'USA', 'Boise');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CAK', 'OH', 'USA', 'Akron');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LEX', 'KY', 'USA', 'Lexington');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CAE', 'SC', 'USA', 'Columbia');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MLI', 'IL', 'USA', 'Moline');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PVD', 'RI', 'USA', 'Providence');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CHA', 'TN', 'USA', 'Chattanooga');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CHO', 'VA', 'USA', 'Charlottesville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MGM', 'AL', 'USA', 'Montgomery');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ILM', 'NC', 'USA', 'Wilmington');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CRW', 'WV', 'USA', 'Charleston');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ALB', 'NY', 'USA', 'Albany');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AVL', 'NC', 'USA', 'Asheville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ROA', 'VA', 'USA', 'Roanoke');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TRI', 'TN', 'USA', 'Bristol');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MDT', 'PA', 'USA', 'Harrisburg');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PFN', 'FL', 'USA', 'Panama City');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ABE', 'PA', 'USA', 'Allentown');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MYR', 'SC', 'USA', 'Myrtle Beach');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PHF', 'VA', 'USA', 'Newport News');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GNV', 'FL', 'USA', 'Gainesville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GRR', 'MI', 'USA', 'Grand Rapids');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FNT', 'MI', 'USA', 'Flint');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FAY', 'NC', 'USA', 'Fayetteville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MEI', 'MS', 'USA', 'Meridian');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MSN', 'WI', 'USA', 'Madison');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FSM', 'AR', 'USA', 'Fort Smith');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LAW', 'OK', 'USA', 'Lawton');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OAJ', 'NC', 'USA', 'Jacksonville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DHN', 'AL', 'USA', 'Dothan');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DSM', 'IA', 'USA', 'Des Moines');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AGS', 'GA', 'USA', 'Augusta');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CSG', 'GA', 'USA', 'Columbus');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SHV', 'LA', 'USA', 'Shreveport');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BQK', 'GA', 'USA', 'Brunswick');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('VLD', 'GA', 'USA', 'Valdosta');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HHH', 'NA', 'USA', 'NA');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SGF', 'MO', 'USA', 'Springfield');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LYH', 'VA', 'USA', 'Lynchburg');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MLU', 'LA', 'USA', 'Monroe');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BMI', 'IL', 'USA', 'Bloomington');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EVV', 'IN', 'USA', 'Evansville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EWN', 'NC', 'USA', 'New Bern');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FLO', 'SC', 'USA', 'Florence');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GTR', 'MS', 'USA', 'Columbus-Starkville-West Point');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SBN', 'IN', 'USA', 'South Bend');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MHT', 'NH', 'USA', 'Manchester');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GRK', 'TX', 'USA', 'Killeen');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AVP', 'PA', 'USA', 'Wilkes-Barre/Scranton');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LFT', 'LA', 'USA', 'Lafayette');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PIA', 'IL', 'USA', 'Peoria');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ATW', 'WI', 'USA', 'Appleton');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FWA', 'IN', 'USA', 'Fort Wayne');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CID', 'IA', 'USA', 'Cedar Rapids');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AEX', 'LA', 'USA', 'Alexandria');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LWB', 'WV', 'USA', 'Lewisburg');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ABY', 'GA', 'USA', 'Albany');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EYW', 'FL', 'USA', 'Key West');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MDW', 'IL', 'USA', 'Chicago');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ITO', 'HI', 'USA', 'Hilo');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MQT', 'NA', 'USA', 'NA');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SBP', 'CA', 'USA', 'San Luis Obispo');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SBA', 'CA', 'USA', 'Santa Barbara');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MRY', 'CA', 'USA', 'Monterey');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CLL', 'TX', 'USA', 'College Station');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AMA', 'TX', 'USA', 'Amarillo');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TXK', 'AR', 'USA', 'Texarkana');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LRD', 'TX', 'USA', 'Laredo');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ACT', 'TX', 'USA', 'Waco');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LBB', 'TX', 'USA', 'Lubbock');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CRP', 'TX', 'USA', 'Corpus Christi');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MAF', 'TX', 'USA', 'Midland');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GGG', 'TX', 'USA', 'Longview');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ABI', 'TX', 'USA', 'Abilene');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CMI', 'IL', 'USA', 'Champaign/Urbana');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TYR', 'TX', 'USA', 'Tyler');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ROW', 'NM', 'USA', 'Roswell');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GJT', 'CO', 'USA', 'Grand Junction');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GRB', 'WI', 'USA', 'Green Bay');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RST', 'MN', 'USA', 'Rochester');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LSE', 'WI', 'USA', 'La Crosse');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DBQ', 'IA', 'USA', 'Dubuque');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TVC', 'MI', 'USA', 'Traverse City');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AZO', 'MI', 'USA', 'Kalamazoo');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DAL', 'TX', 'USA', 'Dallas');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CWA', 'WI', 'USA', 'Mosinee');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TOL', 'OH', 'USA', 'Toledo');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FSD', 'SD', 'USA', 'Sioux Falls');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FAR', 'ND', 'USA', 'Fargo');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MBS', 'MI', 'USA', 'Saginaw');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DLH', 'MN', 'USA', 'Duluth');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BIS', 'ND', 'USA', 'Bismarck');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GFK', 'ND', 'USA', 'Grand Forks');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MOT', 'ND', 'USA', 'Minot');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LAN', 'MI', 'USA', 'Lansing');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BIL', 'MT', 'USA', 'Billings');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RAP', 'SD', 'USA', 'Rapid City');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BZN', 'MT', 'USA', 'Bozeman');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HTS', 'WV', 'USA', 'Huntington');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BGR', 'ME', 'USA', 'Bangor');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SUN', 'ID', 'USA', 'Hailey');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CPR', 'WY', 'USA', 'Casper');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HLN', 'MT', 'USA', 'Helena');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FCA', 'MT', 'USA', 'Kalispell');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('JAC', 'WY', 'USA', 'Jackson');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LWS', 'ID', 'USA', 'Lewiston');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PSC', 'WA', 'USA', 'Pasco');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IDA', 'ID', 'USA', 'Idaho Falls');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ACV', 'CA', 'USA', 'Arcata/Eureka');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('COD', 'WY', 'USA', 'Cody');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BTM', 'MT', 'USA', 'Butte');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EUG', 'OR', 'USA', 'Eugene');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GTF', 'MT', 'USA', 'Great Falls');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MSO', 'MT', 'USA', 'Missoula');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MFR', 'OR', 'USA', 'Medford');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RDM', 'OR', 'USA', 'Redmond');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BFL', 'CA', 'USA', 'Bakersfield');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IYK', 'CA', 'USA', 'Inyokern');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SMX', 'CA', 'USA', 'Santa Maria');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OXR', 'CA', 'USA', 'Oxnard');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RDD', 'CA', 'USA', 'Redding');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PMD', 'CA', 'USA', 'Palmdale');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CEC', 'CA', 'USA', 'Crescent City');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SGU', 'UT', 'USA', 'St George');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MOD', 'CA', 'USA', 'Modesto');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('YUM', 'AZ', 'USA', 'Yuma');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OTH', 'OR', 'USA', 'North Bend');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CIC', 'CA', 'USA', 'Chico');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CLD', 'NA', 'USA', 'NA');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LMT', 'OR', 'USA', 'Klamath Falls');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IPL', 'CA', 'USA', 'Imperial');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MTJ', 'CO', 'USA', 'Montrose');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LNK', 'NE', 'USA', 'Lincoln');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SPI', 'IL', 'USA', 'Springfield');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ASE', 'CO', 'USA', 'Aspen');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HDN', 'CO', 'USA', 'Hayden');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CDC', 'UT', 'USA', 'Cedar City');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EKO', 'NV', 'USA', 'Elko');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PIH', 'ID', 'USA', 'Pocatello');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TWF', 'ID', 'USA', 'Twin Falls');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GCC', 'WY', 'USA', 'Gillette');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RKS', 'WY', 'USA', 'Rock Springs');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ISP', 'NY', 'USA', 'Islip');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HRL', 'TX', 'USA', 'Harlingen');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LCH', 'LA', 'USA', 'Lake Charles');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BRO', 'TX', 'USA', 'Brownsville');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FLG', 'AZ', 'USA', 'Flagstaff');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DRO', 'CO', 'USA', 'Durango');
INSERT INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GUC', 'CO', 'USA', 'Gunnison');
