INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LAX', 'CA', 'USA', Los Angeles);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('JFK', 'NY', 'USA', New York);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SFO', 'CA', 'USA', San Francisco);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LAS', 'NV', 'USA', Las Vegas);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ORD', 'IL', 'USA', Chicago);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LGA', 'NY', 'USA', New York);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('STT', 'VI', 'USA', Charlotte Amalie);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MIA', 'FL', 'USA', Miami);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DFW', 'TX', 'USA', Dallas-Fort Worth);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PHL', 'PA', 'USA', Philadelphia);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('STL', 'MO', 'USA', St Louis);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DCA', 'VA', 'USA', Arlington);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IAH', 'TX', 'USA', Houston);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BNA', 'TN', 'USA', Nashville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HNL', 'HI', 'USA', Honolulu);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OGG', 'HI', 'USA', Kahului);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BOS', 'MA', 'USA', Boston);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IAD', 'VA', 'USA', Chantilly);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EWR', 'NJ', 'USA', Newark);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SAN', 'CA', 'USA', San Diego);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MCO', 'FL', 'USA', Orlando);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('KOA', 'HI', 'USA', Kailua/Kona);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SEA', 'WA', 'USA', Seattle);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TUS', 'AZ', 'USA', Tucson);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LIH', 'HI', 'USA', Lihue);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RDU', 'NC', 'USA', Raleigh);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TPA', 'FL', 'USA', Tampa);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PHX', 'AZ', 'USA', Phoenix);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BWI', 'MD', 'USA', Baltimore);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SNA', 'CA', 'USA', Santa Ana);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SJC', 'CA', 'USA', San Jose);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RSW', 'FL', 'USA', Ft. Myers);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MCI', 'MO', 'USA', Kansas City);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MSY', 'LA', 'USA', New Orleans);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BHM', 'AL', 'USA', Birmingham);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PSP', 'CA', 'USA', Palm Springs);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SAT', 'TX', 'USA', San Antonio);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('XNA', 'AR', 'USA', Fayetteville/Springdale/Rogers);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DEN', 'CO', 'USA', Denver);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PDX', 'OR', 'USA', Portland);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ATL', 'GA', 'USA', Atlanta);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BDL', 'CT', 'USA', Windsor Locks);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RIC', 'VA', 'USA', Richmond);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MFE', 'TX', 'USA', McAllen);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FAT', 'CA', 'USA', Fresno);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ELP', 'TX', 'USA', El Paso);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MSP', 'MN', 'USA', Minneapolis);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ONT', 'CA', 'USA', Ontario);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OKC', 'OK', 'USA', Oklahoma City);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IND', 'IN', 'USA', Indianapolis);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ABQ', 'NM', 'USA', Albuquerque);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PBI', 'FL', 'USA', West Palm Beach);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SJU', 'PR', 'USA', San Juan);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('JAX', 'FL', 'USA', Jacksonville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AUS', 'TX', 'USA', Austin);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MEM', 'TN', 'USA', Memphis);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SLC', 'UT', 'USA', Salt Lake City);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DTW', 'MI', 'USA', Detroit);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BUR', 'CA', 'USA', Burbank);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FLL', 'FL', 'USA', Ft. Lauderdale);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CMH', 'OH', 'USA', Columbus);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RNO', 'NV', 'USA', Reno);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ICT', 'KS', 'USA', Wichita);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TUL', 'OK', 'USA', Tulsa);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('COS', 'CO', 'USA', Colorado Springs);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ORF', 'VA', 'USA', Norfolk);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SMF', 'CA', 'USA', Sacramento);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CLT', 'NC', 'USA', Charlotte);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DAY', 'OH', 'USA', Dayton);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('STX', 'VI', 'USA', Christiansted);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OMA', 'NE', 'USA', Omaha);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GSO', 'NC', 'USA', Greensboro);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SDF', 'KY', 'USA', Louisville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HSV', 'AL', 'USA', Huntsville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EGE', 'CO', 'USA', Eagle);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SCC', 'AK', 'USA', Deadhorse);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BRW', 'AK', 'USA', Barrow);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ANC', 'AK', 'USA', Anchorage);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OTZ', 'AK', 'USA', Kotzebue);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OME', 'AK', 'USA', Nome);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ADQ', 'AK', 'USA', Kodiak);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BET', 'AK', 'USA', Bethel);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FAI', 'AK', 'USA', Fairbanks);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('KTN', 'AK', 'USA', Ketchikan);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('JNU', 'AK', 'USA', Juneau);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('YAK', 'AK', 'USA', Yakutat);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CDV', 'AK', 'USA', Cordova);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SIT', 'AK', 'USA', Sitka);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PSG', 'AK', 'USA', Petersburg);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('WRG', 'AK', 'USA', Wrangell);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ADK', 'AK', 'USA', Adak);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OAK', 'CA', 'USA', Oakland);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LGB', 'CA', 'USA', Long Beach);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GEG', 'WA', 'USA', Spokane);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BUF', 'NY', 'USA', Buffalo);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SYR', 'NY', 'USA', Syracuse);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BTV', 'VT', 'USA', Burlington);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ROC', 'NY', 'USA', Rochester);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SRQ', 'FL', 'USA', Sarasota);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SWF', 'NY', 'USA', Newburgh);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HPN', 'NY', 'USA', White Plains);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PWM', 'ME', 'USA', Portland);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HOU', 'TX', 'USA', Houston);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BQN', 'PR', 'USA', Aguadilla);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PSE', 'PR', 'USA', Ponce);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PIT', 'PA', 'USA', Pittsburgh);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CLE', 'OH', 'USA', Cleveland);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BTR', 'LA', 'USA', Baton Rouge);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CVG', 'KY', 'USA', Covington);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GSP', 'SC', 'USA', Greer);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GPT', 'MS', 'USA', Gulfport-Biloxi);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TLH', 'FL', 'USA', Tallahassee);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PNS', 'FL', 'USA', Pensacola);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SAV', 'GA', 'USA', Savannah);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DAB', 'FL', 'USA', Daytona Beach);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MOB', 'AL', 'USA', Mobile);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LIT', 'AR', 'USA', Little Rock);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MLB', 'FL', 'USA', Melbourne);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('JAN', 'MS', 'USA', Jackson);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MKE', 'WI', 'USA', Milwaukee);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CHS', 'SC', 'USA', Charleston);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('VPS', 'FL', 'USA', Valparaiso);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TYS', 'TN', 'USA', Knoxville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BOI', 'ID', 'USA', Boise);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CAK', 'OH', 'USA', Akron);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LEX', 'KY', 'USA', Lexington);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CAE', 'SC', 'USA', Columbia);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MLI', 'IL', 'USA', Moline);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PVD', 'RI', 'USA', Providence);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CHA', 'TN', 'USA', Chattanooga);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CHO', 'VA', 'USA', Charlottesville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MGM', 'AL', 'USA', Montgomery);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ILM', 'NC', 'USA', Wilmington);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CRW', 'WV', 'USA', Charleston);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ALB', 'NY', 'USA', Albany);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AVL', 'NC', 'USA', Asheville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ROA', 'VA', 'USA', Roanoke);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TRI', 'TN', 'USA', Bristol);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MDT', 'PA', 'USA', Harrisburg);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PFN', 'FL', 'USA', Panama City);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ABE', 'PA', 'USA', Allentown);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MYR', 'SC', 'USA', Myrtle Beach);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PHF', 'VA', 'USA', Newport News);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GNV', 'FL', 'USA', Gainesville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GRR', 'MI', 'USA', Grand Rapids);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FNT', 'MI', 'USA', Flint);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FAY', 'NC', 'USA', Fayetteville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MEI', 'MS', 'USA', Meridian);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MSN', 'WI', 'USA', Madison);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FSM', 'AR', 'USA', Fort Smith);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LAW', 'OK', 'USA', Lawton);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OAJ', 'NC', 'USA', Jacksonville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DHN', 'AL', 'USA', Dothan);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DSM', 'IA', 'USA', Des Moines);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AGS', 'GA', 'USA', Augusta);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CSG', 'GA', 'USA', Columbus);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SHV', 'LA', 'USA', Shreveport);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BQK', 'GA', 'USA', Brunswick);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('VLD', 'GA', 'USA', Valdosta);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HHH', 'NA', 'USA', NA);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SGF', 'MO', 'USA', Springfield);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LYH', 'VA', 'USA', Lynchburg);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MLU', 'LA', 'USA', Monroe);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BMI', 'IL', 'USA', Bloomington);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EVV', 'IN', 'USA', Evansville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EWN', 'NC', 'USA', New Bern);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FLO', 'SC', 'USA', Florence);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GTR', 'MS', 'USA', Columbus-Starkville-West Point);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SBN', 'IN', 'USA', South Bend);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MHT', 'NH', 'USA', Manchester);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GRK', 'TX', 'USA', Killeen);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AVP', 'PA', 'USA', Wilkes-Barre/Scranton);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LFT', 'LA', 'USA', Lafayette);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PIA', 'IL', 'USA', Peoria);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ATW', 'WI', 'USA', Appleton);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FWA', 'IN', 'USA', Fort Wayne);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CID', 'IA', 'USA', Cedar Rapids);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AEX', 'LA', 'USA', Alexandria);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LWB', 'WV', 'USA', Lewisburg);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ABY', 'GA', 'USA', Albany);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EYW', 'FL', 'USA', Key West);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MDW', 'IL', 'USA', Chicago);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ITO', 'HI', 'USA', Hilo);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MQT', 'NA', 'USA', NA);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SBP', 'CA', 'USA', San Luis Obispo);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SBA', 'CA', 'USA', Santa Barbara);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MRY', 'CA', 'USA', Monterey);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CLL', 'TX', 'USA', College Station);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AMA', 'TX', 'USA', Amarillo);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TXK', 'AR', 'USA', Texarkana);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LRD', 'TX', 'USA', Laredo);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ACT', 'TX', 'USA', Waco);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LBB', 'TX', 'USA', Lubbock);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CRP', 'TX', 'USA', Corpus Christi);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MAF', 'TX', 'USA', Midland);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GGG', 'TX', 'USA', Longview);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ABI', 'TX', 'USA', Abilene);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CMI', 'IL', 'USA', Champaign/Urbana);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TYR', 'TX', 'USA', Tyler);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ROW', 'NM', 'USA', Roswell);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GJT', 'CO', 'USA', Grand Junction);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GRB', 'WI', 'USA', Green Bay);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RST', 'MN', 'USA', Rochester);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LSE', 'WI', 'USA', La Crosse);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DBQ', 'IA', 'USA', Dubuque);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TVC', 'MI', 'USA', Traverse City);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('AZO', 'MI', 'USA', Kalamazoo);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DAL', 'TX', 'USA', Dallas);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CWA', 'WI', 'USA', Mosinee);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TOL', 'OH', 'USA', Toledo);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FSD', 'SD', 'USA', Sioux Falls);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FAR', 'ND', 'USA', Fargo);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MBS', 'MI', 'USA', Saginaw);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DLH', 'MN', 'USA', Duluth);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BIS', 'ND', 'USA', Bismarck);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GFK', 'ND', 'USA', Grand Forks);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MOT', 'ND', 'USA', Minot);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LAN', 'MI', 'USA', Lansing);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BIL', 'MT', 'USA', Billings);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RAP', 'SD', 'USA', Rapid City);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BZN', 'MT', 'USA', Bozeman);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HTS', 'WV', 'USA', Huntington);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BGR', 'ME', 'USA', Bangor);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SUN', 'ID', 'USA', Hailey);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CPR', 'WY', 'USA', Casper);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HLN', 'MT', 'USA', Helena);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FCA', 'MT', 'USA', Kalispell);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('JAC', 'WY', 'USA', Jackson);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LWS', 'ID', 'USA', Lewiston);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PSC', 'WA', 'USA', Pasco);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IDA', 'ID', 'USA', Idaho Falls);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ACV', 'CA', 'USA', Arcata/Eureka);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('COD', 'WY', 'USA', Cody);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BTM', 'MT', 'USA', Butte);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EUG', 'OR', 'USA', Eugene);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GTF', 'MT', 'USA', Great Falls);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MSO', 'MT', 'USA', Missoula);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MFR', 'OR', 'USA', Medford);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RDM', 'OR', 'USA', Redmond);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BFL', 'CA', 'USA', Bakersfield);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IYK', 'CA', 'USA', Inyokern);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SMX', 'CA', 'USA', Santa Maria);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OXR', 'CA', 'USA', Oxnard);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RDD', 'CA', 'USA', Redding);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PMD', 'CA', 'USA', Palmdale);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CEC', 'CA', 'USA', Crescent City);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SGU', 'UT', 'USA', St George);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MOD', 'CA', 'USA', Modesto);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('YUM', 'AZ', 'USA', Yuma);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('OTH', 'OR', 'USA', North Bend);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CIC', 'CA', 'USA', Chico);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CLD', 'NA', 'USA', NA);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LMT', 'OR', 'USA', Klamath Falls);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('IPL', 'CA', 'USA', Imperial);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('MTJ', 'CO', 'USA', Montrose);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LNK', 'NE', 'USA', Lincoln);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('SPI', 'IL', 'USA', Springfield);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ASE', 'CO', 'USA', Aspen);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HDN', 'CO', 'USA', Hayden);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('CDC', 'UT', 'USA', Cedar City);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('EKO', 'NV', 'USA', Elko);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('PIH', 'ID', 'USA', Pocatello);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('TWF', 'ID', 'USA', Twin Falls);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GCC', 'WY', 'USA', Gillette);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('RKS', 'WY', 'USA', Rock Springs);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('ISP', 'NY', 'USA', Islip);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('HRL', 'TX', 'USA', Harlingen);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('LCH', 'LA', 'USA', Lake Charles);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('BRO', 'TX', 'USA', Brownsville);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('FLG', 'AZ', 'USA', Flagstaff);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('DRO', 'CO', 'USA', Durango);
INSERTO INTO Aeropuerto (IATA, estado, pais, ciudad) VALUES ('GUC', 'CO', 'USA', Gunnison);
