INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LAX', 'Los Angeles International' , 'CA', 'USA', 'Los Angeles');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('JFK', 'John F Kennedy Intl' , 'NY', 'USA', 'New York');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SFO', 'San Francisco International' , 'CA', 'USA', 'San Francisco');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LAS', 'McCarran International' , 'NV', 'USA', 'Las Vegas');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ORD', 'Chicago OHare International' , 'IL', 'USA', 'Chicago');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LGA', 'LaGuardia' , 'NY', 'USA', 'New York');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('STT', 'Cyril E. King' , 'VI', 'USA', 'Charlotte Amalie');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MIA', 'Miami International' , 'FL', 'USA', 'Miami');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DFW', 'Dallas-Fort Worth International' , 'TX', 'USA', 'Dallas-Fort Worth');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PHL', 'Philadelphia Intl' , 'PA', 'USA', 'Philadelphia');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('STL', 'Lambert-St Louis International' , 'MO', 'USA', 'St Louis');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DCA', 'Ronald Reagan Washington National' , 'VA', 'USA', 'Arlington');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('IAH', 'George Bush Intercontinental' , 'TX', 'USA', 'Houston');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BNA', 'Nashville International' , 'TN', 'USA', 'Nashville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('HNL', 'Honolulu International' , 'HI', 'USA', 'Honolulu');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('OGG', 'Kahului' , 'HI', 'USA', 'Kahului');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BOS', 'Gen Edw L Logan Intl' , 'MA', 'USA', 'Boston');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('IAD', 'Washington Dulles International' , 'VA', 'USA', 'Chantilly');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('EWR', 'Newark Intl' , 'NJ', 'USA', 'Newark');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SAN', 'San Diego International-Lindbergh' , 'CA', 'USA', 'San Diego');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MCO', 'Orlando International' , 'FL', 'USA', 'Orlando');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('KOA', 'Kona International At Keahole' , 'HI', 'USA', 'Kailua/Kona');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SEA', 'Seattle-Tacoma Intl' , 'WA', 'USA', 'Seattle');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('TUS', 'Tucson International' , 'AZ', 'USA', 'Tucson');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LIH', 'Lihue' , 'HI', 'USA', 'Lihue');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('RDU', 'Raleigh-Durham International' , 'NC', 'USA', 'Raleigh');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('TPA', 'Tampa International' , 'FL', 'USA', 'Tampa');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PHX', 'Phoenix Sky Harbor International' , 'AZ', 'USA', 'Phoenix');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BWI', 'Baltimore-Washington International' , 'MD', 'USA', 'Baltimore');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SNA', 'John Wayne /Orange Co' , 'CA', 'USA', 'Santa Ana');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SJC', 'San Jose International' , 'CA', 'USA', 'San Jose');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('RSW', 'Southwest Florida International' , 'FL', 'USA', 'Ft. Myers');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MCI', 'Kansas City International' , 'MO', 'USA', 'Kansas City');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MSY', 'New Orleans International' , 'LA', 'USA', 'New Orleans');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BHM', 'Birmingham International' , 'AL', 'USA', 'Birmingham');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PSP', 'Palm Springs International' , 'CA', 'USA', 'Palm Springs');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SAT', 'San Antonio International' , 'TX', 'USA', 'San Antonio');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('XNA', 'Northwest Arkansas Regional' , 'AR', 'USA', 'Fayetteville/Springdale/Rogers');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DEN', 'Denver Intl' , 'CO', 'USA', 'Denver');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PDX', 'Portland Intl' , 'OR', 'USA', 'Portland');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ATL', 'William B Hartsfield-Atlanta Intl' , 'GA', 'USA', 'Atlanta');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BDL', 'Bradley International' , 'CT', 'USA', 'Windsor Locks');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('RIC', 'Richmond International' , 'VA', 'USA', 'Richmond');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MFE', 'McAllen Miller International' , 'TX', 'USA', 'McAllen');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FAT', 'Fresno Yosemite International' , 'CA', 'USA', 'Fresno');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ELP', 'El Paso International' , 'TX', 'USA', 'El Paso');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MSP', 'Minneapolis-St Paul Intl' , 'MN', 'USA', 'Minneapolis');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ONT', 'Ontario International' , 'CA', 'USA', 'Ontario');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('OKC', 'Will Rogers World' , 'OK', 'USA', 'Oklahoma City');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('IND', 'Indianapolis International' , 'IN', 'USA', 'Indianapolis');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ABQ', 'Albuquerque International' , 'NM', 'USA', 'Albuquerque');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PBI', 'Palm Beach International' , 'FL', 'USA', 'West Palm Beach');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SJU', 'Luis Munoz Marin International' , 'PR', 'USA', 'San Juan');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('JAX', 'Jacksonville International' , 'FL', 'USA', 'Jacksonville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('AUS', 'Austin-Bergstrom International' , 'TX', 'USA', 'Austin');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MEM', 'Memphis International' , 'TN', 'USA', 'Memphis');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SLC', 'Salt Lake City Intl' , 'UT', 'USA', 'Salt Lake City');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DTW', 'Detroit Metropolitan-Wayne County' , 'MI', 'USA', 'Detroit');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BUR', 'Burbank-Glendale-Pasadena' , 'CA', 'USA', 'Burbank');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FLL', 'Fort Lauderdale-Hollywood Intl' , 'FL', 'USA', 'Ft. Lauderdale');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CMH', 'Port Columbus Intl' , 'OH', 'USA', 'Columbus');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('RNO', 'Reno/Tahoe International' , 'NV', 'USA', 'Reno');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ICT', 'Wichita Mid-Continent' , 'KS', 'USA', 'Wichita');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('TUL', 'Tulsa International' , 'OK', 'USA', 'Tulsa');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('COS', 'City of Colorado Springs Muni' , 'CO', 'USA', 'Colorado Springs');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ORF', 'Norfolk International' , 'VA', 'USA', 'Norfolk');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SMF', 'Sacramento International' , 'CA', 'USA', 'Sacramento');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CLT', 'Charlotte/Douglas International' , 'NC', 'USA', 'Charlotte');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DAY', 'James M Cox Dayton Intl' , 'OH', 'USA', 'Dayton');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('STX', 'Henry E. Rohlsen' , 'VI', 'USA', 'Christiansted');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('OMA', 'Eppley Airfield' , 'NE', 'USA', 'Omaha');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GSO', 'Piedmont Triad International' , 'NC', 'USA', 'Greensboro');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SDF', 'Louisville International-Standiford' , 'KY', 'USA', 'Louisville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('HSV', 'Huntsville International' , 'AL', 'USA', 'Huntsville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('EGE', 'Eagle County Regional' , 'CO', 'USA', 'Eagle');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SCC', 'Deadhorse' , 'AK', 'USA', 'Deadhorse');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BRW', 'Wiley Post Will Rogers Memorial' , 'AK', 'USA', 'Barrow');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ANC', 'Ted Stevens Anchorage International' , 'AK', 'USA', 'Anchorage');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('OTZ', 'Ralph Wien Memorial' , 'AK', 'USA', 'Kotzebue');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('OME', 'Nome' , 'AK', 'USA', 'Nome');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ADQ', 'Kodiak' , 'AK', 'USA', 'Kodiak');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BET', 'Bethel' , 'AK', 'USA', 'Bethel');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FAI', 'Fairbanks International' , 'AK', 'USA', 'Fairbanks');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('KTN', 'Ketchikan International' , 'AK', 'USA', 'Ketchikan');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('JNU', 'Juneau International' , 'AK', 'USA', 'Juneau');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('YAK', 'Yakutat' , 'AK', 'USA', 'Yakutat');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CDV', 'Merle K (Mudhole) Smith' , 'AK', 'USA', 'Cordova');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SIT', 'Sitka' , 'AK', 'USA', 'Sitka');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PSG', 'James C. Johnson Petersburg' , 'AK', 'USA', 'Petersburg');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('WRG', 'Wrangell' , 'AK', 'USA', 'Wrangell');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ADK', 'Adak' , 'AK', 'USA', 'Adak');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('OAK', 'Metropolitan Oakland International' , 'CA', 'USA', 'Oakland');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LGB', 'Long Beach (Daugherty )' , 'CA', 'USA', 'Long Beach');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GEG', 'Spokane Intl' , 'WA', 'USA', 'Spokane');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BUF', 'Buffalo Niagara Intl' , 'NY', 'USA', 'Buffalo');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SYR', 'Syracuse-Hancock Intl' , 'NY', 'USA', 'Syracuse');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BTV', 'Burlington International' , 'VT', 'USA', 'Burlington');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ROC', 'Greater Rochester Intl' , 'NY', 'USA', 'Rochester');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SRQ', 'Sarasota Bradenton International' , 'FL', 'USA', 'Sarasota');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SWF', 'Stewart' , 'NY', 'USA', 'Newburgh');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('HPN', 'Westchester Cty' , 'NY', 'USA', 'White Plains');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PWM', 'Portland International Jetport' , 'ME', 'USA', 'Portland');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('HOU', 'William P Hobby' , 'TX', 'USA', 'Houston');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BQN', 'Rafael Hernandez' , 'PR', 'USA', 'Aguadilla');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PSE', 'Mercedita' , 'PR', 'USA', 'Ponce');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PIT', 'Pittsburgh International' , 'PA', 'USA', 'Pittsburgh');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CLE', 'Cleveland-Hopkins Intl' , 'OH', 'USA', 'Cleveland');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BTR', 'Baton Rouge Metropolitan, Ryan' , 'LA', 'USA', 'Baton Rouge');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CVG', 'Cincinnati Northern Kentucky Intl' , 'KY', 'USA', 'Covington');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GSP', 'Greenville-Spartanburg' , 'SC', 'USA', 'Greer');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GPT', 'Gulfport-Biloxi Regional' , 'MS', 'USA', 'Gulfport-Biloxi');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('TLH', 'Tallahassee Regional' , 'FL', 'USA', 'Tallahassee');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PNS', 'Pensacola Regional' , 'FL', 'USA', 'Pensacola');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SAV', 'Savannah International' , 'GA', 'USA', 'Savannah');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DAB', 'Daytona Beach International' , 'FL', 'USA', 'Daytona Beach');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MOB', 'Mobile Regional' , 'AL', 'USA', 'Mobile');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LIT', 'Adams' , 'AR', 'USA', 'Little Rock');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MLB', 'Melbourne International' , 'FL', 'USA', 'Melbourne');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('JAN', 'Jackson International' , 'MS', 'USA', 'Jackson');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MKE', 'General Mitchell International' , 'WI', 'USA', 'Milwaukee');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CHS', 'Charleston AFB/International' , 'SC', 'USA', 'Charleston');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('VPS', 'Eglin Air Force Base' , 'FL', 'USA', 'Valparaiso');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('TYS', 'McGhee-Tyson' , 'TN', 'USA', 'Knoxville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BOI', 'Boise Air Terminal' , 'ID', 'USA', 'Boise');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CAK', 'Akron-Canton Regional' , 'OH', 'USA', 'Akron');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LEX', 'Blue Grass' , 'KY', 'USA', 'Lexington');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CAE', 'Columbia Metropolitan' , 'SC', 'USA', 'Columbia');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MLI', 'Quad City' , 'IL', 'USA', 'Moline');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PVD', 'Theodore F Green State' , 'RI', 'USA', 'Providence');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CHA', 'Lovell' , 'TN', 'USA', 'Chattanooga');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CHO', 'Charlottesville-Albermarle' , 'VA', 'USA', 'Charlottesville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MGM', 'Montgomery Regional Apt' , 'AL', 'USA', 'Montgomery');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ILM', 'Wilmington International' , 'NC', 'USA', 'Wilmington');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CRW', 'Yeager' , 'WV', 'USA', 'Charleston');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ALB', 'Albany Cty' , 'NY', 'USA', 'Albany');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('AVL', 'Asheville Regional' , 'NC', 'USA', 'Asheville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ROA', 'Roanoke Regional/ Woodrum' , 'VA', 'USA', 'Roanoke');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('TRI', 'Tri-Cities Regional' , 'TN', 'USA', 'Bristol');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MDT', 'Harrisburg Intl' , 'PA', 'USA', 'Harrisburg');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PFN', 'Panama City-Bay County International' , 'FL', 'USA', 'Panama City');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ABE', 'Lehigh Valley International' , 'PA', 'USA', 'Allentown');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MYR', 'Myrtle Beach International' , 'SC', 'USA', 'Myrtle Beach');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PHF', 'Newport News/Williamsburg International' , 'VA', 'USA', 'Newport News');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GNV', 'Gainesville Regional' , 'FL', 'USA', 'Gainesville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GRR', 'Kent County International' , 'MI', 'USA', 'Grand Rapids');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FNT', 'Bishop' , 'MI', 'USA', 'Flint');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FAY', 'Fayetteville Municipal' , 'NC', 'USA', 'Fayetteville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MEI', 'Key' , 'MS', 'USA', 'Meridian');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MSN', 'Dane County Regional' , 'WI', 'USA', 'Madison');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FSM', 'Fort Smith Regional' , 'AR', 'USA', 'Fort Smith');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LAW', 'Lawton-Ft Sill Regional' , 'OK', 'USA', 'Lawton');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('OAJ', 'Albert J Ellis' , 'NC', 'USA', 'Jacksonville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DHN', 'Dothan' , 'AL', 'USA', 'Dothan');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DSM', 'Des Moines International' , 'IA', 'USA', 'Des Moines');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('AGS', 'Bush' , 'GA', 'USA', 'Augusta');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CSG', 'Columbus Metropolitan' , 'GA', 'USA', 'Columbus');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SHV', 'Shreveport Regional' , 'LA', 'USA', 'Shreveport');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BQK', 'Glynco Jetport' , 'GA', 'USA', 'Brunswick');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('VLD', 'Valdosta Regional' , 'GA', 'USA', 'Valdosta');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('HHH', 'Hilton Head' , 'NA', 'USA', 'NA');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SGF', 'Springfield-Branson Regional' , 'MO', 'USA', 'Springfield');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LYH', 'Lynchburg Municipal-Preston Glenn' , 'VA', 'USA', 'Lynchburg');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MLU', 'Monroe Regional' , 'LA', 'USA', 'Monroe');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BMI', 'Central Illinois Regional' , 'IL', 'USA', 'Bloomington');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('EVV', 'Evansville Regional' , 'IN', 'USA', 'Evansville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('EWN', 'Craven County Regional' , 'NC', 'USA', 'New Bern');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FLO', 'Florence Regional' , 'SC', 'USA', 'Florence');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GTR', 'Golden Triangle Regional' , 'MS', 'USA', 'Columbus-Starkville-West Point');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SBN', 'South Bend Regional' , 'IN', 'USA', 'South Bend');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MHT', 'Manchester' , 'NH', 'USA', 'Manchester');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GRK', 'Robert Gray AAF' , 'TX', 'USA', 'Killeen');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('AVP', 'Wilkes-Barre/Scranton Intl' , 'PA', 'USA', 'Wilkes-Barre/Scranton');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LFT', 'Lafayette Regional' , 'LA', 'USA', 'Lafayette');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PIA', 'Greater Peoria Regional' , 'IL', 'USA', 'Peoria');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ATW', 'Outagamie County Regional' , 'WI', 'USA', 'Appleton');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FWA', 'Fort Wayne International' , 'IN', 'USA', 'Fort Wayne');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CID', 'Eastern Iowa' , 'IA', 'USA', 'Cedar Rapids');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('AEX', 'Alexandria International' , 'LA', 'USA', 'Alexandria');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LWB', 'Greenbrier Valley' , 'WV', 'USA', 'Lewisburg');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ABY', 'Southwest Georgia Regional' , 'GA', 'USA', 'Albany');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('EYW', 'Key West International' , 'FL', 'USA', 'Key West');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MDW', 'Chicago Midway' , 'IL', 'USA', 'Chicago');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ITO', 'Hilo International' , 'HI', 'USA', 'Hilo');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MQT', 'Marquette County Airport' , 'NA', 'USA', 'NA');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SBP', 'San Luis Obispo Co-McChesney' , 'CA', 'USA', 'San Luis Obispo');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SBA', 'Santa Barbara Municipal' , 'CA', 'USA', 'Santa Barbara');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MRY', 'Monterey Peninsula' , 'CA', 'USA', 'Monterey');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CLL', 'Easterwood' , 'TX', 'USA', 'College Station');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('AMA', 'Amarillo International' , 'TX', 'USA', 'Amarillo');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('TXK', 'Texarkana Regional-Webb' , 'AR', 'USA', 'Texarkana');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LRD', 'Laredo International' , 'TX', 'USA', 'Laredo');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ACT', 'Waco Regional' , 'TX', 'USA', 'Waco');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LBB', 'Lubbock International' , 'TX', 'USA', 'Lubbock');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CRP', 'Corpus Christi International' , 'TX', 'USA', 'Corpus Christi');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MAF', 'Midland International' , 'TX', 'USA', 'Midland');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GGG', 'Gregg County' , 'TX', 'USA', 'Longview');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ABI', 'Abilene Regional' , 'TX', 'USA', 'Abilene');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CMI', 'University of Illinois-Willard' , 'IL', 'USA', 'Champaign/Urbana');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('TYR', 'Tyler Pounds' , 'TX', 'USA', 'Tyler');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ROW', 'Roswell Industrial Air Center' , 'NM', 'USA', 'Roswell');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GJT', 'Walker' , 'CO', 'USA', 'Grand Junction');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GRB', 'Austin Straubel International' , 'WI', 'USA', 'Green Bay');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('RST', 'Rochester International' , 'MN', 'USA', 'Rochester');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LSE', 'La Crosse Municipal' , 'WI', 'USA', 'La Crosse');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DBQ', 'Dubuque Municipal' , 'IA', 'USA', 'Dubuque');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('TVC', 'Cherry Capital' , 'MI', 'USA', 'Traverse City');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('AZO', 'Kalamazoo County' , 'MI', 'USA', 'Kalamazoo');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DAL', 'Dallas Love' , 'TX', 'USA', 'Dallas');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CWA', 'Central Wisconsin' , 'WI', 'USA', 'Mosinee');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('TOL', 'Toledo Express' , 'OH', 'USA', 'Toledo');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FSD', 'Joe Foss' , 'SD', 'USA', 'Sioux Falls');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FAR', 'Hector International' , 'ND', 'USA', 'Fargo');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MBS', 'Mbs International' , 'MI', 'USA', 'Saginaw');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DLH', 'Duluth International' , 'MN', 'USA', 'Duluth');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BIS', 'Bismarck Municipal' , 'ND', 'USA', 'Bismarck');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GFK', 'Grand Forks International' , 'ND', 'USA', 'Grand Forks');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MOT', 'Minot International' , 'ND', 'USA', 'Minot');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LAN', 'Capital City' , 'MI', 'USA', 'Lansing');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BIL', 'Billings Logan Intl' , 'MT', 'USA', 'Billings');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('RAP', 'Rapid City Regional' , 'SD', 'USA', 'Rapid City');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BZN', 'Gallatin' , 'MT', 'USA', 'Bozeman');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('HTS', 'Tri-State/Walker-Long' , 'WV', 'USA', 'Huntington');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BGR', 'Bangor International' , 'ME', 'USA', 'Bangor');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SUN', 'Friedman Memorial' , 'ID', 'USA', 'Hailey');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CPR', 'Natrona County Intl' , 'WY', 'USA', 'Casper');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('HLN', 'Helena Regional' , 'MT', 'USA', 'Helena');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FCA', 'Glacier Park Intl' , 'MT', 'USA', 'Kalispell');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('JAC', 'Jackson Hole' , 'WY', 'USA', 'Jackson');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LWS', 'Lewiston-Nez Perce County' , 'ID', 'USA', 'Lewiston');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PSC', 'Tri-Cities' , 'WA', 'USA', 'Pasco');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('IDA', 'Idaho Falls Regional' , 'ID', 'USA', 'Idaho Falls');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ACV', 'Arcata' , 'CA', 'USA', 'Arcata/Eureka');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('COD', 'Yellowstone Regional' , 'WY', 'USA', 'Cody');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BTM', 'Bert Mooney' , 'MT', 'USA', 'Butte');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('EUG', 'Mahlon Sweet' , 'OR', 'USA', 'Eugene');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GTF', 'Great Falls Intl' , 'MT', 'USA', 'Great Falls');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MSO', 'Missoula International' , 'MT', 'USA', 'Missoula');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MFR', 'Rogue Valley International' , 'OR', 'USA', 'Medford');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('RDM', 'Roberts' , 'OR', 'USA', 'Redmond');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BFL', 'Meadows' , 'CA', 'USA', 'Bakersfield');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('IYK', 'Inyokern' , 'CA', 'USA', 'Inyokern');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SMX', 'Santa Maria Pub/Capt G Allan Hancock' , 'CA', 'USA', 'Santa Maria');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('OXR', 'Oxnard' , 'CA', 'USA', 'Oxnard');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('RDD', 'Redding Municipal' , 'CA', 'USA', 'Redding');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PMD', 'Palmdale Production Flight' , 'CA', 'USA', 'Palmdale');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CEC', 'Jack McNamara' , 'CA', 'USA', 'Crescent City');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SGU', 'St George Muni' , 'UT', 'USA', 'St George');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MOD', 'Modesto City-County-Harry Sham' , 'CA', 'USA', 'Modesto');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('YUM', 'Yuma MCAS-Yuma International' , 'AZ', 'USA', 'Yuma');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('OTH', 'North Bend Muni' , 'OR', 'USA', 'North Bend');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CIC', 'Chico Municipal' , 'CA', 'USA', 'Chico');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CLD', 'MC Clellan-Palomar Airport' , 'NA', 'USA', 'NA');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LMT', 'Klamath Falls International' , 'OR', 'USA', 'Klamath Falls');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('IPL', 'Imperial County' , 'CA', 'USA', 'Imperial');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('MTJ', 'Montrose Regional' , 'CO', 'USA', 'Montrose');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LNK', 'Lincoln Municipal' , 'NE', 'USA', 'Lincoln');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('SPI', 'Capital' , 'IL', 'USA', 'Springfield');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ASE', 'Aspen-Pitkin Co/Sardy' , 'CO', 'USA', 'Aspen');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('HDN', 'Yampa Valley' , 'CO', 'USA', 'Hayden');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('CDC', 'Cedar City Muni' , 'UT', 'USA', 'Cedar City');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('EKO', 'Elko Regional' , 'NV', 'USA', 'Elko');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('PIH', 'Pocatello Regional' , 'ID', 'USA', 'Pocatello');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('TWF', 'Joslin Field - Magic Valley' , 'ID', 'USA', 'Twin Falls');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GCC', 'Gillette-Campbell County' , 'WY', 'USA', 'Gillette');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('RKS', 'Rock Springs-Sweetwater County' , 'WY', 'USA', 'Rock Springs');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('ISP', 'Long Island - MacArthur' , 'NY', 'USA', 'Islip');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('HRL', 'Valley International' , 'TX', 'USA', 'Harlingen');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('LCH', 'Lake Charles Regional' , 'LA', 'USA', 'Lake Charles');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('BRO', 'Brownsville/S.Padre Island International' , 'TX', 'USA', 'Brownsville');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('FLG', 'Flagstaff Pulliam' , 'AZ', 'USA', 'Flagstaff');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('DRO', 'Durango-La Plata County' , 'CO', 'USA', 'Durango');
INSERT INTO Aeropuerto (IATA, NOMBRE, estado, pais, ciudad) VALUES ('GUC', 'Gunnison County' , 'CO', 'USA', 'Gunnison');
