INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('323', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('328', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('449', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('673', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('708', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('756', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('1059', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('1563', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('1712', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('2125', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('2221', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('2277', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('2388', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('2447', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('2545', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('2558', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('2762', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('2924', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4099', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4367', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4411', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4704', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4707', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4717', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4720', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4758', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4761', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4792', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4793', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4794', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4795', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4796', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4844', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4856', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4874', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4889', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4903', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('4924', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5127', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5129', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5146', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5147', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5162', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5172', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5233', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5299', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5360', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5363', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5554', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5757', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5775', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5779', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5801', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5810', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5844', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5912', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5965', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5993', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5996', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('5999', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6027', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6035', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6615', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6621', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6627', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6641', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6710', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6714', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6810', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6813', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6818', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6827', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6829', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6833', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6845', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('6846', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('7046', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('7051', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('8220', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('8485', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('8576', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('9299', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('9354', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('9488', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('9596', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('9681', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('10696', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('10890', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11134', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11284', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11308', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11406', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11412', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11413', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11421', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11422', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11424', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11425', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11432', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11434', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11435', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11443', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11474', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11480', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('11568', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('12100', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('12165', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('12495', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('12657', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('12700', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('12808', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('13017', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('13078', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('13423', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('14077', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('15472', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('15608', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('15620', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('15629', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('15915', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('15918', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('15924', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('16241', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('16243', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('16383', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('17063', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('17066', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('17490', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('17505', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('17772', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('17780', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('17841', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('17844', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('17871', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('17948', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('17951', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('18017', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('18032', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('18035', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('18064', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('18096', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('18105', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('18107', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('18505', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('18831', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('19399', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('19400', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('19411', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('19712', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('19805', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('19806', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('19997', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20002', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20102', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20149', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20232', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20266', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20317', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20440', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20442', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20449', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20455', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20475', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20483', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20510', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20523', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20525', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20585', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20736', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20819', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20823', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20828', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20831', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20837', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20846', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20868', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20871', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20881', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20891', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20916', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20937', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20947', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20952', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20954', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20973', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20976', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20981', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20985', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('20988', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('21004', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('21010', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('21013', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('21064', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('21088', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('21121', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('21128', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('21186', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('21250', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('21252', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('21253', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23579', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23588', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23594', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23595', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23637', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23681', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23726', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23752', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23791', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23807', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23886', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23900', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('23937', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24049', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24050', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24256', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24284', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24328', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24342', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24382', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24438', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24439', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24468', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24500', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24505', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24728', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24730', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24736', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('24776', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('25070', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('25108', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('25194', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('25849', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('25913', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('25915', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('25920', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('25923', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26096', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26212', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26234', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26237', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26240', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26242', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26258', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26260', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26330', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26331', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26332', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26376', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26383', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26385', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26423', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26449', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26534', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26544', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26601', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26616', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26708', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('26860', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('27093', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('27218', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('27227', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('27228', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('27279', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('27308', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('27326', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('27508', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('27542', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('27553', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('28007', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('28369', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('28437', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('28478', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('28551', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('28692', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('28788', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('29112', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('29125', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('29147', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('29187', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('29383', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('29439', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('29442', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('29649', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('29895', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('30012', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('30069', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('30484', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('30488', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('30522', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('30560', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('30671', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('30718', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('30930', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('30977', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('30988', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('31037', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('31310', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('31342', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('31369', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('32072', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('32356', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('32593', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('32682', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('33205', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('33365', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('33528', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('33833', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('33960', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('33971', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('34238', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('34388', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('34524', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('34537', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('34611', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('34622', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('34833', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('34838', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35304', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35312', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35314', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35326', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35389', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35391', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35500', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35571', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35596', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35597', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35683', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35699', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35728', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35729', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35762', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35799', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35815', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35846', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35848', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('35996', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('36183', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('36231', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('36245', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('36291', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('36317', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('36771', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('36999', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('37001', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('37062', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('37120', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('37765', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('37925', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('37951', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('38077', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('38118', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('38639', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('39007', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('39265', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('39313', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('39525', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('39554', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('39615', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('39829', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('40101', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('40102', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('40247', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('40490', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('40605', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('40888', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('40998', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('41100', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('41151', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('41959', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('42113', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('44412', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('44418', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('44568', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('44948', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('45078', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('45310', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('46056', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('46166', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('46203', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('46241', 'National Air System');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('46963', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47004', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47107', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47204', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47229', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47237', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47243', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47258', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47386', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47573', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47659', 'Weather');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47836', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47837', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('47851', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('48184', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('48249', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('48250', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('48299', 'Carrier');
INSERT INTO Cancelacion (ID_VUELO, causa) VALUES ('48300', 'Carrier');
