INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('0', '323', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('1', '328', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('2', '449', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('3', '673', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('4', '708', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('5', '756', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('6', '1059', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('7', '1563', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('8', '1712', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('9', '2125', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('10', '2221', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('11', '2277', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('12', '2388', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('13', '2447', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('14', '2545', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('15', '2558', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('16', '2762', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('17', '2924', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('18', '4099', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('19', '4367', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('20', '4411', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('21', '4704', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('22', '4707', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('23', '4717', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('24', '4720', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('25', '4758', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('26', '4761', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('27', '4792', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('28', '4793', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('29', '4794', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('30', '4795', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('31', '4796', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('32', '4844', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('33', '4856', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('34', '4874', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('35', '4889', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('36', '4903', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('37', '4924', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('38', '5127', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('39', '5129', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('40', '5146', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('41', '5147', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('42', '5162', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('43', '5172', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('44', '5233', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('45', '5299', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('46', '5360', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('47', '5363', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('48', '5554', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('49', '5757', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('50', '5775', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('51', '5779', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('52', '5801', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('53', '5810', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('54', '5844', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('55', '5912', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('56', '5965', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('57', '5993', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('58', '5996', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('59', '5999', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('60', '6027', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('61', '6035', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('62', '6615', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('63', '6621', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('64', '6627', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('65', '6641', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('66', '6710', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('67', '6714', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('68', '6810', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('69', '6813', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('70', '6818', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('71', '6827', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('72', '6829', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('73', '6833', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('74', '6845', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('75', '6846', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('76', '7046', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('77', '7051', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('78', '8220', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('79', '8485', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('80', '8576', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('81', '9299', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('82', '9354', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('83', '9488', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('84', '9596', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('85', '9681', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('86', '10696', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('87', '10890', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('88', '11134', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('89', '11284', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('90', '11308', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('91', '11406', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('92', '11412', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('93', '11413', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('94', '11421', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('95', '11422', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('96', '11424', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('97', '11425', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('98', '11432', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('99', '11434', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('100', '11435', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('101', '11443', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('102', '11474', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('103', '11480', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('104', '11568', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('105', '12100', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('106', '12165', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('107', '12495', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('108', '12657', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('109', '12700', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('110', '12808', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('111', '13017', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('112', '13078', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('113', '13423', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('114', '14077', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('115', '15472', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('116', '15608', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('117', '15620', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('118', '15629', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('119', '15915', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('120', '15918', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('121', '15924', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('122', '16241', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('123', '16243', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('124', '16383', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('125', '17063', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('126', '17066', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('127', '17490', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('128', '17505', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('129', '17772', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('130', '17780', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('131', '17841', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('132', '17844', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('133', '17871', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('134', '17948', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('135', '17951', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('136', '18017', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('137', '18032', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('138', '18035', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('139', '18064', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('140', '18096', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('141', '18105', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('142', '18107', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('143', '18505', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('144', '18831', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('145', '19399', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('146', '19400', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('147', '19411', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('148', '19712', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('149', '19805', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('150', '19806', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('151', '19997', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('152', '20002', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('153', '20102', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('154', '20149', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('155', '20232', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('156', '20266', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('157', '20317', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('158', '20440', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('159', '20442', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('160', '20449', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('161', '20455', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('162', '20475', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('163', '20483', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('164', '20510', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('165', '20523', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('166', '20525', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('167', '20585', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('168', '20736', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('169', '20819', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('170', '20823', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('171', '20828', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('172', '20831', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('173', '20837', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('174', '20846', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('175', '20868', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('176', '20871', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('177', '20881', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('178', '20891', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('179', '20916', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('180', '20937', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('181', '20947', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('182', '20952', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('183', '20954', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('184', '20973', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('185', '20976', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('186', '20981', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('187', '20985', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('188', '20988', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('189', '21004', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('190', '21010', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('191', '21013', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('192', '21064', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('193', '21088', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('194', '21121', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('195', '21128', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('196', '21186', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('197', '21250', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('198', '21252', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('199', '21253', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('200', '23579', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('201', '23588', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('202', '23594', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('203', '23595', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('204', '23637', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('205', '23681', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('206', '23726', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('207', '23752', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('208', '23791', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('209', '23807', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('210', '23886', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('211', '23900', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('212', '23937', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('213', '24049', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('214', '24050', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('215', '24256', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('216', '24284', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('217', '24328', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('218', '24342', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('219', '24382', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('220', '24438', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('221', '24439', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('222', '24468', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('223', '24500', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('224', '24505', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('225', '24728', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('226', '24730', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('227', '24736', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('228', '24776', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('229', '25070', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('230', '25108', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('231', '25194', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('232', '25849', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('233', '25913', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('234', '25915', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('235', '25920', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('236', '25923', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('237', '26096', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('238', '26212', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('239', '26234', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('240', '26237', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('241', '26240', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('242', '26242', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('243', '26258', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('244', '26260', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('245', '26330', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('246', '26331', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('247', '26332', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('248', '26376', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('249', '26383', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('250', '26385', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('251', '26423', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('252', '26449', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('253', '26534', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('254', '26544', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('255', '26601', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('256', '26616', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('257', '26708', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('258', '26860', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('259', '27093', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('260', '27218', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('261', '27227', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('262', '27228', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('263', '27279', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('264', '27308', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('265', '27326', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('266', '27508', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('267', '27542', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('268', '27553', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('269', '28007', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('270', '28369', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('271', '28437', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('272', '28478', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('273', '28551', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('274', '28692', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('275', '28788', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('276', '29112', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('277', '29125', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('278', '29147', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('279', '29187', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('280', '29383', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('281', '29439', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('282', '29442', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('283', '29649', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('284', '29895', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('285', '30012', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('286', '30069', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('287', '30484', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('288', '30488', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('289', '30522', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('290', '30560', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('291', '30671', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('292', '30718', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('293', '30930', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('294', '30977', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('295', '30988', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('296', '31037', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('297', '31310', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('298', '31342', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('299', '31369', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('300', '32072', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('301', '32356', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('302', '32593', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('303', '32682', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('304', '33205', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('305', '33365', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('306', '33528', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('307', '33833', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('308', '33960', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('309', '33971', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('310', '34238', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('311', '34388', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('312', '34524', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('313', '34537', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('314', '34611', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('315', '34622', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('316', '34833', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('317', '34838', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('318', '35304', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('319', '35312', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('320', '35314', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('321', '35326', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('322', '35389', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('323', '35391', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('324', '35500', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('325', '35571', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('326', '35596', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('327', '35597', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('328', '35683', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('329', '35699', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('330', '35728', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('331', '35729', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('332', '35762', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('333', '35799', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('334', '35815', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('335', '35846', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('336', '35848', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('337', '35996', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('338', '36183', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('339', '36231', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('340', '36245', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('341', '36291', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('342', '36317', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('343', '36771', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('344', '36999', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('345', '37001', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('346', '37062', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('347', '37120', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('348', '37765', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('349', '37925', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('350', '37951', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('351', '38077', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('352', '38118', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('353', '38639', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('354', '39007', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('355', '39265', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('356', '39313', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('357', '39525', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('358', '39554', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('359', '39615', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('360', '39829', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('361', '40101', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('362', '40102', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('363', '40247', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('364', '40490', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('365', '40605', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('366', '40888', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('367', '40998', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('368', '41100', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('369', '41151', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('370', '41959', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('371', '42113', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('372', '44412', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('373', '44418', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('374', '44568', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('375', '44948', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('376', '45078', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('377', '45310', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('378', '46056', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('379', '46166', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('380', '46203', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('381', '46241', 'National Air System');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('382', '46963', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('383', '47004', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('384', '47107', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('385', '47204', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('386', '47229', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('387', '47237', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('388', '47243', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('389', '47258', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('390', '47386', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('391', '47573', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('392', '47659', 'Weather');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('393', '47836', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('394', '47837', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('395', '47851', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('396', '48184', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('397', '48249', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('398', '48250', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('399', '48299', 'Carrier');
INSERT INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('400', '48300', 'Carrier');
