INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('0', '324', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('1', '329', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('2', '450', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('3', '674', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('4', '709', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('5', '757', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('6', '1060', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('7', '1564', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('8', '1713', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('9', '2126', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('10', '2222', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('11', '2278', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('12', '2389', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('13', '2448', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('14', '2546', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('15', '2559', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('16', '2763', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('17', '2925', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('18', '4100', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('19', '4368', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('20', '4412', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('21', '4705', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('22', '4708', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('23', '4718', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('24', '4721', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('25', '4759', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('26', '4762', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('27', '4793', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('28', '4794', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('29', '4795', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('30', '4796', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('31', '4797', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('32', '4845', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('33', '4857', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('34', '4875', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('35', '4890', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('36', '4904', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('37', '4925', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('38', '5128', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('39', '5130', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('40', '5147', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('41', '5148', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('42', '5163', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('43', '5173', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('44', '5234', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('45', '5300', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('46', '5361', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('47', '5364', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('48', '5555', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('49', '5758', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('50', '5776', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('51', '5780', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('52', '5802', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('53', '5811', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('54', '5845', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('55', '5913', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('56', '5966', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('57', '5994', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('58', '5997', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('59', '6000', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('60', '6028', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('61', '6036', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('62', '6616', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('63', '6622', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('64', '6628', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('65', '6642', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('66', '6711', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('67', '6715', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('68', '6811', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('69', '6814', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('70', '6819', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('71', '6828', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('72', '6830', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('73', '6834', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('74', '6846', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('75', '6847', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('76', '7047', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('77', '7052', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('78', '8221', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('79', '8486', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('80', '8577', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('81', '9300', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('82', '9355', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('83', '9489', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('84', '9597', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('85', '9682', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('86', '10697', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('87', '10891', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('88', '11135', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('89', '11285', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('90', '11309', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('91', '11407', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('92', '11413', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('93', '11414', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('94', '11422', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('95', '11423', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('96', '11425', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('97', '11426', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('98', '11433', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('99', '11435', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('100', '11436', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('101', '11444', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('102', '11475', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('103', '11481', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('104', '11569', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('105', '12101', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('106', '12166', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('107', '12496', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('108', '12658', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('109', '12701', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('110', '12809', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('111', '13018', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('112', '13079', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('113', '13424', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('114', '14078', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('115', '15473', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('116', '15609', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('117', '15621', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('118', '15630', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('119', '15916', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('120', '15919', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('121', '15925', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('122', '16242', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('123', '16244', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('124', '16384', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('125', '17064', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('126', '17067', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('127', '17491', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('128', '17506', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('129', '17773', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('130', '17781', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('131', '17842', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('132', '17845', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('133', '17872', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('134', '17949', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('135', '17952', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('136', '18018', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('137', '18033', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('138', '18036', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('139', '18065', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('140', '18097', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('141', '18106', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('142', '18108', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('143', '18506', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('144', '18832', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('145', '19400', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('146', '19401', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('147', '19412', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('148', '19713', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('149', '19806', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('150', '19807', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('151', '19998', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('152', '20003', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('153', '20103', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('154', '20150', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('155', '20233', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('156', '20267', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('157', '20318', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('158', '20441', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('159', '20443', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('160', '20450', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('161', '20456', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('162', '20476', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('163', '20484', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('164', '20511', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('165', '20524', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('166', '20526', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('167', '20586', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('168', '20737', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('169', '20820', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('170', '20824', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('171', '20829', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('172', '20832', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('173', '20838', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('174', '20847', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('175', '20869', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('176', '20872', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('177', '20882', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('178', '20892', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('179', '20917', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('180', '20938', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('181', '20948', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('182', '20953', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('183', '20955', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('184', '20974', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('185', '20977', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('186', '20982', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('187', '20986', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('188', '20989', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('189', '21005', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('190', '21011', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('191', '21014', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('192', '21065', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('193', '21089', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('194', '21122', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('195', '21129', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('196', '21187', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('197', '21251', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('198', '21253', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('199', '21254', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('200', '23580', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('201', '23589', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('202', '23595', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('203', '23596', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('204', '23638', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('205', '23682', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('206', '23727', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('207', '23753', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('208', '23792', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('209', '23808', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('210', '23887', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('211', '23901', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('212', '23938', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('213', '24050', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('214', '24051', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('215', '24257', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('216', '24285', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('217', '24329', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('218', '24343', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('219', '24383', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('220', '24439', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('221', '24440', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('222', '24469', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('223', '24501', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('224', '24506', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('225', '24729', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('226', '24731', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('227', '24737', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('228', '24777', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('229', '25071', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('230', '25109', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('231', '25195', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('232', '25850', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('233', '25914', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('234', '25916', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('235', '25921', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('236', '25924', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('237', '26097', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('238', '26213', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('239', '26235', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('240', '26238', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('241', '26241', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('242', '26243', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('243', '26259', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('244', '26261', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('245', '26331', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('246', '26332', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('247', '26333', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('248', '26377', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('249', '26384', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('250', '26386', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('251', '26424', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('252', '26450', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('253', '26535', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('254', '26545', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('255', '26602', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('256', '26617', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('257', '26709', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('258', '26861', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('259', '27094', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('260', '27219', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('261', '27228', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('262', '27229', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('263', '27280', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('264', '27309', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('265', '27327', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('266', '27509', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('267', '27543', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('268', '27554', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('269', '28008', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('270', '28370', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('271', '28438', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('272', '28479', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('273', '28552', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('274', '28693', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('275', '28789', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('276', '29113', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('277', '29126', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('278', '29148', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('279', '29188', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('280', '29384', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('281', '29440', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('282', '29443', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('283', '29650', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('284', '29896', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('285', '30013', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('286', '30070', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('287', '30485', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('288', '30489', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('289', '30523', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('290', '30561', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('291', '30672', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('292', '30719', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('293', '30931', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('294', '30978', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('295', '30989', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('296', '31038', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('297', '31311', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('298', '31343', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('299', '31370', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('300', '32073', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('301', '32357', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('302', '32594', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('303', '32683', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('304', '33206', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('305', '33366', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('306', '33529', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('307', '33834', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('308', '33961', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('309', '33972', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('310', '34239', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('311', '34389', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('312', '34525', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('313', '34538', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('314', '34612', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('315', '34623', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('316', '34834', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('317', '34839', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('318', '35305', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('319', '35313', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('320', '35315', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('321', '35327', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('322', '35390', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('323', '35392', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('324', '35501', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('325', '35572', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('326', '35597', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('327', '35598', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('328', '35684', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('329', '35700', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('330', '35729', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('331', '35730', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('332', '35763', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('333', '35800', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('334', '35816', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('335', '35847', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('336', '35849', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('337', '35997', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('338', '36184', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('339', '36232', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('340', '36246', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('341', '36292', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('342', '36318', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('343', '36772', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('344', '37000', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('345', '37002', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('346', '37063', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('347', '37121', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('348', '37766', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('349', '37926', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('350', '37952', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('351', '38078', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('352', '38119', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('353', '38640', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('354', '39008', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('355', '39266', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('356', '39314', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('357', '39526', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('358', '39555', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('359', '39616', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('360', '39830', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('361', '40102', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('362', '40103', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('363', '40248', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('364', '40491', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('365', '40606', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('366', '40889', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('367', '40999', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('368', '41101', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('369', '41152', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('370', '41960', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('371', '42114', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('372', '44413', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('373', '44419', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('374', '44569', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('375', '44949', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('376', '45079', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('377', '45311', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('378', '46057', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('379', '46167', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('380', '46204', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('381', '46242', 'National Air System');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('382', '46964', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('383', '47005', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('384', '47108', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('385', '47205', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('386', '47230', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('387', '47238', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('388', '47244', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('389', '47259', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('390', '47387', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('391', '47574', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('392', '47660', 'Weather');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('393', '47837', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('394', '47838', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('395', '47852', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('396', '48185', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('397', '48250', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('398', '48251', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('399', '48300', 'Carrier');
INSERTO INTO Cancelacion (ID, ID_VUELO, causa) VALUES ('400', '48301', 'Carrier');
