INSERT INTO Fabricante (Fabricante) VALUES ('BOEING');
INSERT INTO Fabricante (Fabricante) VALUES ('DOUGLAS');
INSERT INTO Fabricante (Fabricante) VALUES ('HELIO');
INSERT INTO Fabricante (Fabricante) VALUES ('BEECH');
INSERT INTO Fabricante (Fabricante) VALUES ('PIPER');
INSERT INTO Fabricante (Fabricante) VALUES ('AERO COMMANDER');
INSERT INTO Fabricante (Fabricante) VALUES ('AEROSPATIALE');
INSERT INTO Fabricante (Fabricante) VALUES ('SIKORSKY');
INSERT INTO Fabricante (Fabricante) VALUES ('LEBLANC GLENN T');
INSERT INTO Fabricante (Fabricante) VALUES ('CESSNA');
INSERT INTO Fabricante (Fabricante) VALUES ('BAUMAN RANDY');
INSERT INTO Fabricante (Fabricante) VALUES ('GULFSTREAM AEROSPACE');
INSERT INTO Fabricante (Fabricante) VALUES ('MARZ BARRY');
INSERT INTO Fabricante (Fabricante) VALUES ('RAVEN');
INSERT INTO Fabricante (Fabricante) VALUES ('FRIEDEMANN JON');
INSERT INTO Fabricante (Fabricante) VALUES ('BELL');
INSERT INTO Fabricante (Fabricante) VALUES ('DEHAVILLAND');
INSERT INTO Fabricante (Fabricante) VALUES ('MORSE GEORGE JR');
INSERT INTO Fabricante (Fabricante) VALUES ('AVIAT AIRCRAFT INC');
INSERT INTO Fabricante (Fabricante) VALUES ('AIRBUS');
INSERT INTO Fabricante (Fabricante) VALUES ('EMBRAER');
INSERT INTO Fabricante (Fabricante) VALUES ('BOMBARDIER INC');
INSERT INTO Fabricante (Fabricante) VALUES ('AEROSPATIALE/ALENIA');
