INSERTO INTO Fabricante (Fabricante) VALUES ('BOEING');
INSERTO INTO Fabricante (Fabricante) VALUES ('DOUGLAS');
INSERTO INTO Fabricante (Fabricante) VALUES ('HELIO');
INSERTO INTO Fabricante (Fabricante) VALUES ('BEECH');
INSERTO INTO Fabricante (Fabricante) VALUES ('PIPER');
INSERTO INTO Fabricante (Fabricante) VALUES ('AERO COMMANDER');
INSERTO INTO Fabricante (Fabricante) VALUES ('AEROSPATIALE');
INSERTO INTO Fabricante (Fabricante) VALUES ('SIKORSKY');
INSERTO INTO Fabricante (Fabricante) VALUES ('LEBLANC GLENN T');
INSERTO INTO Fabricante (Fabricante) VALUES ('CESSNA');
INSERTO INTO Fabricante (Fabricante) VALUES ('BAUMAN RANDY');
INSERTO INTO Fabricante (Fabricante) VALUES ('GULFSTREAM AEROSPACE');
INSERTO INTO Fabricante (Fabricante) VALUES ('MARZ BARRY');
INSERTO INTO Fabricante (Fabricante) VALUES ('RAVEN');
INSERTO INTO Fabricante (Fabricante) VALUES ('FRIEDEMANN JON');
INSERTO INTO Fabricante (Fabricante) VALUES ('BELL');
INSERTO INTO Fabricante (Fabricante) VALUES ('DEHAVILLAND');
INSERTO INTO Fabricante (Fabricante) VALUES ('MORSE GEORGE JR');
INSERTO INTO Fabricante (Fabricante) VALUES ('AVIAT AIRCRAFT INC');
INSERTO INTO Fabricante (Fabricante) VALUES ('AIRBUS');
INSERTO INTO Fabricante (Fabricante) VALUES ('EMBRAER');
INSERTO INTO Fabricante (Fabricante) VALUES ('BOMBARDIER INC');
INSERTO INTO Fabricante (Fabricante) VALUES ('AEROSPATIALE/ALENIA');
